/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Friend } from "./Friend";
export * as factories from "./factories";
export { Friend__factory } from "./factories/Friend__factory";
